### ISSUE TITLE
agda-pkg should not overwrite existing defaults and libraries

### ISSUE THREAD

**Issue by soimort** [agda/agda-pkg#35]
A user may already have her own `.agda/defaults` and `.agda/libraries` before using agda-pkg.
Currently `apkg` seems to overwrite these without any warning, which is not always desirable.

I propose three possible improvements:
1) Show a warning and ask the user before overwriting anything.
2) Generate some backup files in the same directory.
3) Keep existing settings in the managed `defaults` and `libraries` files.

**Comment by jonaprieto** [comment]
Used from now, the option 1:

Show a warning and ask the user before overwriting anything.

**Comment by soimort** [comment]
Great. Thanks for the fix!
