### ISSUE TITLE
Example usage with NixOS

### ISSUE THREAD

**Issue by bbarker** [agda/agda-pkg#37]
I have an example Nix config I could add to the README if interested; this also allows automatic configuration of emacs (still allowing customization) for agda: https://github.com/bbarker/LearningAgda

**Comment by jonaprieto** [comment]
Sure, open a pull request to see what it's about.

Btw, what do you mean by "automatic configuration emacs"? is this about running "agda-mode setup"?

**Comment by bbarker** [comment]
> Sure, open a pull request to see what it's about.

Will do, have a few minor clean-up things and README clarifications first.

> Btw, what do you mean by "automatic configuration emacs"? is this about running "agda-mode setup"?

Yes, but it will use a custom .emacs file in the local directory that loads `~/.emacs`, then creates an alias `mymacs` that can be used to use the local `.emacs`
