### ISSUE TITLE
apkg not installed

### ISSUE THREAD

**Issue by michel1948** [agda/agda-pkg#39]
I have installed agda-pkg with the command "pip3 install agda-pkg. But the command apkg is not installed.

**Comment by jonaprieto** [comment]
Which is your OS ? and which Python, Pip version have you installed? This issue is maybe because your shell doesn't find the commands installed by pip3. Maybe [this](https://opensource.com/article/19/5/python-3-default-mac) could help?

**Comment by michel1948** [comment]
With the example given on https://github.com/agda/agda-pkg, I believed that apkg was installed on /usr/bin. But now with your answer (and a similar problem with cabal), I found apkg (and agda-pkg) installed in $HOME/.local/bin/

**Comment by michel1948** [comment]
With the example given on https://github.com/agda/agda-pkg, I believed that apkg was installed on /usr/bin. But now with your answer (and a similar problem with cabal), I found apkg (and agda-pkg) installed in $HOME/.local/bin/
