### ISSUE TITLE
Indexed web release of PLFA instead of dev release

### ISSUE THREAD

**Issue by wenkokke** [agda/agda-pkg#43]
The current README lists the indexed version of PLFA as "stable-web-2019.09", which is the release without any Agda code in there. (Also, the versioning is out of date, "stable-web-2019.09" is called web-19.08.)

The releases you'd want to index, if at all, are the dev releases. The latest dev release is "dev-20.07".

**Comment by jonaprieto** [comment]
Thanks. I think I fixed it, I'll stop indexing web-19.08. Now, one can install the dev version
by using `apkg install plfa` or specifying the version explicitly.

```
$ apkg install plfa@dev-20.07
```

You might need (recommend) to update the database by running`apkg clean && apkg init`.
Just reopen if something doesn't work as one expect.
