### ISSUE TITLE
Generate HTML

### ISSUE THREAD

**Issue by cspollard** [agda/agda-pkg#44]
Hello,

I'm new to Agda, and one thing I find very useful for learning are the clickable html versions of libraries that can be generated via the --html option. Is generating a global html file something agda-pkg might be capable of? That would be a very nice feature if not.

Best,

Chris

**Comment by jonaprieto** [comment]
Hi Chris,

> I'm new to Agda, and one thing I find very useful for learning are the clickable html versions of libraries that can be generated via the --html option. 

Yes, this is a really nice feature.

> Is generating a global html file something agda-pkg might be capable of? 

No. To generate the html you need to compile the source code as you said, and agda-pkg
does not compile the libraries when it tries to install them. So, you have to do it manually.
It would be very nice to have one webpage using the current package index where you
can click the html for every library.

**Comment by cspollard** [comment]
Hi Jonathan,

Thanks very much for your response. Do you have a suggestion for a better place to file a feature request?

Best,

Chris

**Comment by jonaprieto** [comment]
I think you can do it on https://github.com/agda/agda or on Zulip channel: agda.zulipchat.com
